//
//  Local.swift
//  Translate it
//
//  Created by iMac on 01/09/21.
//

import Foundation

extension String {
    static let pleaseSignInUsing = "pleaseSignInUsing"
    static let signInToContinue = "signInToContinue"
    static let signInWithApple = "signInWithApple"
    static let signInWithGoogle = "signInWithGoogle"
    static let signInWithEmail = "signInWithEmail"
    static let signIn = "signIn"
    static let email = "email"
    static let password = "password"
    static let signUp = "signUp"
    static let forgotPassword = "forgotPassword"
    static let reset = "reset"
    static let fullName = "fullName"
    static let confirmPassword = "confirmPassword"
    static let verification_link_sent = "verification_link_sent"
    static let passwordMismatched = "passwordMismatched"
    static let please_verify = "please_verify"
    static let password_reset_link_sent = "password_reset_link_sent"
    static let forgotPasswordDisc = "forgotPasswordDisc"
    static let home = "home"
    static let search = "search"
    static let liveTV = "liveTV"
    static let watchlist = "watchlist"
    static let seeAll = "seeAll"
    static let trailer = "trailer"
    static let watchNow = "watchNow"
    static let storyLine = "storyLine"
    static let starCast = "starCast"
    static let moreLikeThis = "moreLikeThis"
    static let season = "season"
    static let availableSources = "availableSources"
    static let readMore = "readMore"
    static let movie = "movie"
    static let series = "series"
    static let all = "all"
    static let searchHere = "searchHere"
    static let genres = "genres"
    static let genre = "genre"
    static let languages = "languages"
    static let noDataFound = "noDataFound"
    static let profile = "profile"
    static let editProfile = "editProfile"
    static let becomeA = "becomeA"
    static let pro = "pro"
    static let update = "update"
    static let notifications = "notifications"
    static let downloads = "downloads"
    static let privacyPolicy = "privacyPolicy"
    static let termsNuses = "termsNuses"
    static let rateThisApp = "rateThisApp"
    static let logout = "logout"
    static let deleteMyAccount = "deleteMyAccount"
    static let areYouSure = "areYouSure"
    static let logoutDes = "logoutDes"
    static let deleteAccountDes = "deleteAccountDes"
    static let subScribeToPro = "subScribeToPro"
    static let subscribeDialogDes = "subscribeDialogDes"
    static let becomeAPro = "becomeAPro"
    static let unlockWithVideoAd = "unlockWithVideoAd"
    static let unlockWithVideoAdDes = "unlockWithVideoAdDes"
    static let watchAd = "watchAd"
    static let restore = "restore"
    static let subscribeToDes = "subscribeToDes"
    static let whyGoWithPro = "whyGoWithPro"
    static let fullyAdFree = "fullyAdFree"
    static let accessToAllPremium = "accessToAllPremium"
    static let technicalSupport = "technicalSupport"
    static let cancelAnyTime = "cancelAnyTime"
    static let proDes = "proDes"
    static let subscribe = "subscribe"
    static let proQ = "proQ"
    static let subscribeTo = "subscribeTo"
    static let proDialogDes = "proDialogDes"
    static let adDialogDes = "adDialogDes"
    static let unlokeWithAd = "unlokeWithAd"
    static let enterSomeThingToSearch = "enterSomeThingToSearch"
    static let noConnection = "noConnection"
    static let noConnectionDes = "noConnectionDes"
    static let goToDownloads = "goToDownloads"
    static let monthPurchaseCardDes = "monthPurchaseCardDes"
    static let yearPurchaseCardDes = "yearPurchaseCardDes"
    static let deleteDownloadDialogDes = "deleteDownloadDialogDes"
    static let removeWatchlistDes = "removeWatchlistDes"
    static let remove = "remove"
    static let delete = "delete"
    static let adSkip = "adSkip"
    static let skipAd = "skipAd"
    static let cantPlayVideo = "cantPlayVideo"
    static let deleteAll = "deleteAll"
    static let deleteAllDes = "deleteAllDes"
    static let topContents = "topContents"
    static let deleteDownload = "deleteDownload"
    static let pauseDownload = "pauseDownload"
    static let resumeDownload = "resumeDownload"
    static let downloading = "downloading"
    static let videoCantPlay = "videoCantPlay"
    static let language = "language"
    static let change = "change"
    static let live = "live"
    static let recentlyWatched = "recentlyWatched"
    static let recentlyWatchedDeleteDes = "recentlyWatchedDeleteDes"
}
