# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Vuga' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'MobileVLCKit'
  
  # TV Streaming Support
  pod 'google-cast-sdk', '~> 4.8.0'
  pod 'CocoaUPnP', '~> 2.0'
  pod 'CocoaAsyncSocket', '~> 7.6'

  # Pods for Vuga

end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                
                # Fix CocoaUPnP module issues
                if target.name == 'CocoaUPnP'
                    config.build_settings['ENABLE_MODULE_VERIFIER'] = 'NO'
                    config.build_settings['MODULE_VERIFIER_SUPPORTED_LANGUAGES'] = 'objective-c objective-c++'
                    config.build_settings['MODULE_VERIFIER_SUPPORTED_LANGUAGE_STANDARDS'] = 'gnu11 gnu++14'
                    config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
                    config.build_settings['DEFINES_MODULE'] = 'YES'
                end
            end
        end
    end
    
    # Fix header search paths for CocoaUPnP
    installer.pods_project.targets.each do |target|
        if target.name == 'CocoaUPnP'
            target.build_configurations.each do |config|
                config.build_settings['HEADER_SEARCH_PATHS'] ||= []
                config.build_settings['HEADER_SEARCH_PATHS'] << '$(inherited)'
                config.build_settings['HEADER_SEARCH_PATHS'] << '${PODS_ROOT}/GCDWebServer/GCDWebServer/Core'
            end
        end
    end
end
