#!/bin/bash

# Configuration
IPA_PATH="./build/Vuga.ipa"
APPLE_ID="YOUR_APPLE_ID@example.com"
APP_PASSWORD="YOUR_APP_SPECIFIC_PASSWORD"

echo "==============================================="
echo "VUGA TV TestFlight Upload"
echo "==============================================="
echo ""
echo "IPA File: $IPA_PATH"
echo "File Size: $(du -h $IPA_PATH | cut -f1)"
echo ""
echo "To upload to TestFlight, you need:"
echo "1. Your Apple ID email address"
echo "2. An app-specific password from https://appleid.apple.com"
echo ""
echo "Run this command with your credentials:"
echo ""
echo "xcrun altool --upload-app \\"
echo "    -f \"$IPA_PATH\" \\"
echo "    -t ios \\"
echo "    -u YOUR_APPLE_ID \\"
echo "    -p YOUR_APP_SPECIFIC_PASSWORD"
echo ""
echo "Or using the newer notarytool (recommended):"
echo ""
echo "xcrun notarytool submit \"$IPA_PATH\" \\"
echo "    --apple-id YOUR_APPLE_ID \\"
echo "    --password YOUR_APP_SPECIFIC_PASSWORD \\"
echo "    --team-id 8TQG9PZ4H5 \\"
echo "    --wait"
echo ""
echo "==============================================="
echo "After upload completes:"
echo "1. Go to App Store Connect"
echo "2. Select your app"
echo "3. Go to TestFlight tab"
echo "4. Your build will appear (may take 5-30 minutes)"
echo "5. Add test information and testers"
echo "==============================================="